FROM ghcr.io/virt-10/blublu-arch:latest AS blublu-resolve

# Support Nvidia Container Runtime (https://developer.nvidia.com/nvidia-container-runtime)
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all

# Install dependencies
RUN sed -i 's/-march=native/-march=x86-64/g' /etc/makepkg.conf \
    && pacman-key --init && pacman-key --populate \
    && pacman -Syu --noconfirm \
    && echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers \
    && pacman -S --clean \
    && pacman -S \
        alsa-lib \
        apr \
        apr-util \
        dbus \
        ffmpeg \
        glu \
        lib32-glu \
        lib32-libglvnd \
        libglvnd \
        libice \
        librsvg \
        libsm \
        libxcrypt-compat \
        libxcursor \
        libxfixes \
        libxi \
        libxinerama \
        libxkbcommon-x11 \
        libxrandr \
        libxtst \
        libxxf86vm \
        lshw \
        mesa-utils \
        mtdev \
        ocl-icd \
        patchelf \
        pipewire-alsa \
        pipewire-pulse \
        vulkan-tools \
        xcb-util \
        xcb-util-cursor \
        xcb-util-image \
        xcb-util-keysyms \
        xcb-util-renderutil \
        xcb-util-wm \
        flac \
        pipewire-jack \
        xdg-desktop-portal-hyprland \
        xdg-desktop-portal-gtk \
        --noconfirm \
    && rm -rf /var/cache/pacman/pkg/* \
    && rm -rf /var/lib/pacman/sync/* \
    && find /var/cache/pacman/ -type f -delete \
    && sed -i '/root ALL=(ALL) NOPASSWD: ALL/d' /etc/sudoers \
    && rm -rf /tmp/* \
    && sed -i 's/-march=x86-64/-march=native/g' /etc/makepkg.conf

# Copy install scripts
COPY system_files /
